// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'constants/env_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: EnvConfig.firebaseWebApiKey,
        appId: EnvConfig.firebaseWebAppId,
        messagingSenderId: EnvConfig.firebaseWebMessagingSenderId,
        projectId: EnvConfig.firebaseWebProjectId,
        authDomain: EnvConfig.firebaseWebAuthDomain,
        storageBucket: EnvConfig.firebaseWebStorageBucket,
        measurementId: EnvConfig.firebaseWebMeasurementId,
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: EnvConfig.firebaseAndroidApiKey,
        appId: EnvConfig.firebaseAndroidAppId,
        messagingSenderId: EnvConfig.firebaseWebMessagingSenderId,
        projectId: EnvConfig.firebaseWebProjectId,
        storageBucket: EnvConfig.firebaseWebStorageBucket,
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: EnvConfig.firebaseIosApiKey,
        appId: EnvConfig.firebaseIosAppId,
        messagingSenderId: EnvConfig.firebaseWebMessagingSenderId,
        projectId: EnvConfig.firebaseWebProjectId,
        authDomain: EnvConfig.firebaseWebAuthDomain,
        storageBucket: EnvConfig.firebaseWebStorageBucket,
        iosClientId: EnvConfig.firebaseIosClientId,
        iosBundleId: EnvConfig.firebaseIosBundleId,
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: EnvConfig.firebaseMacosApiKey,
        appId: EnvConfig.firebaseMacosAppId,
        messagingSenderId: EnvConfig.firebaseWebMessagingSenderId,
        projectId: EnvConfig.firebaseWebProjectId,
        authDomain: EnvConfig.firebaseWebAuthDomain,
        storageBucket: EnvConfig.firebaseWebStorageBucket,
        iosClientId: EnvConfig.firebaseMacosClientId,
        iosBundleId: EnvConfig.firebaseMacosBundleId,
      );
}
