// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMNKPGiv78RK_OAROzaaF-mBe4hL1kdI',
    appId: '1:988277005062:web:ce9ee77a66195228f7dc87',
    messagingSenderId: '988277005062',
    projectId: 'acent-messenger',
    authDomain: 'acent-messenger.firebaseapp.com',
    storageBucket: 'acent-messenger.firebasestorage.app',
    measurementId: 'G-DQ05GY4NZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NMJXU7XiWr-Eb765CCe_wGtC0sYH8sk',
    appId: '1:988277005062:android:fae94b6678534e1af7dc87',
    messagingSenderId: '988277005062',
    projectId: 'acent-messenger',
    storageBucket: 'acent-messenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMNKPGiv78RK_OAROzaaF-mBe4hL1kdI',
    appId: '1:988277005062:ios:ce9ee77a66195228f7dc87',
    messagingSenderId: '988277005062',
    projectId: 'acent-messenger',
    authDomain: 'acent-messenger.firebaseapp.com',
    storageBucket: 'acent-messenger.firebasestorage.app',
    iosClientId:
        '988277005062-abcd1234efgh5678ijkl9012mnop3456.apps.googleusercontent.com',
    iosBundleId: 'com.example.acent_messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMNKPGiv78RK_OAROzaaF-mBe4hL1kdI',
    appId: '1:988277005062:ios:ce9ee77a66195228f7dc87',
    messagingSenderId: '988277005062',
    projectId: 'acent-messenger',
    authDomain: 'acent-messenger.firebaseapp.com',
    storageBucket: 'acent-messenger.firebasestorage.app',
    iosClientId:
        '988277005062-abcd1234efgh5678ijkl9012mnop3456.apps.googleusercontent.com',
    iosBundleId: 'com.example.acent_messenger',
  );
}